apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset-2
  labels:
    app: nginx2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
